### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by lachmanfrantisek** [user-cont/ogr#4]
The `ogr` is a nice, short name, but the 'meaning' should be changed.

Feel free to edit this comment.

| O | G | R |
| - | - | - |
| our | git | rule |
| one | git-forge | revolution |
| open | | rebellion |
| object | | realm |
| only |  | route |
| omnipotent | | rocket |
| | | recipe |
| | | rainbow |
| | | roadway |
| | | reactor |
| | | reunion |
| | | rebel |
| | | ruler |

Possible combinations (and votes):
- our-git-rebel @phracek 
- open-git-rainbow @phracek @TomasTomecek 
- object-git-reactor @phracek 
- the [O]ne [G]it [R]uler @TomasTomecek 
- [O]ne [G]it library to [R]ule @TomasTomecek @jpopelka
- [O]mniponent [G]it-forge [R]uler @jpopelka  @lachmanfrantisek @TomasTomecek

**Comment by phracek** [comment]
I would prefer `our-git-rebel`, `open-git-rainbow` or even `object-git-reactor`

**Comment by TomasTomecek** [comment]
*the [O]ne [G]it library to [R]ule*

*the [O]ne [G]it [R]uler*

**Comment by lachmanfrantisek** [comment]
After discussion with @rpitonak and @jscotka, we decided to go with `* [O]ne [G]it library to [R]ule`.
